# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GjCNOUjLP2iTLszGZYBzTkVJmnhfRxrC
"""

radius=input("\n Enter the radius of the circle:")
radius=int(radius,2)
area=3.14*radius*radius;
print("\n The area of the circle is:", area)