# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cYl-80tIPKQ9FqY_zTHlaRP6iA62JiNX
"""

def find_longest_word(text):
  longest=0
  for words in text.split():
        if len(words) > longest:
            longest = len(words)  
  return longest


input_string = input("Please input a list of words to evaluate: ")
length = find_longest_word(input_string)
print("The longest word  with length", length)