# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OysuietFPzkmq7WCytFnLNLfFuy9F4as
"""

string=input("\n Enter a string:")
print("\n The string in upper case is :",string.upper())
print("\n The string in lower case is :",string.lower())