# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BjGFdMpxnceRiRjYt-2MG5wRu6N5iV6p
"""

print("Input lengths of the triangle sides: ")
a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))

if a == b == c:
	print("Equilateral triangle")
elif a==b or b==c or c==a:
	print("Isosceles triangle")
else:
	print("Scalene triangle")