# -*- coding: utf-8 -*-
"""task8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwlPdFKJcC0HmdRT6w3JP7HZA56pd0yc
"""

def multiply_list(items):
    tot = 1
    
    for x in items:
        tot *= x
    return tot

print("\n The product of list of numbers is:",multiply_list([1,2,3]))