# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17IL0mSoa-r-V9XdBXdb8HE_V5Gcr70Ew
"""

filename=input("\n Enter the file name:")
f_extn = filename.split(".")
print ("The extension of the file is : " + f_extn[1])